<link rel="stylesheet" href="{{ asset('assets/templates/user/css/Linearicons.css') }}">
<link rel="stylesheet" href="{{ asset('assets/templates/user/css/owl.carousel.css') }}">
<link rel="stylesheet" href="{{ asset('assets/templates/user/css/themify-icons.css') }}">
<link rel="stylesheet" href="{{ asset('assets/templates/user/css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/templates/user/css/nice-select.css') }}">
<link rel="stylesheet" href="{{ asset('assets/templates/user/css/nouislider.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/templates/user/css/bootstrap.css') }}">
<link rel="stylesheet" href="{{ asset('assets/templates/user/css/main.css') }}">
<link rel="stylesheet" href="{{ asset('assets/templates/user/css/ion.rangeSlider.css') }}">
<link rel="stylesheet" href="{{ asset('assets/templates/user/css/ion.rangeSlider.skinFlat.css') }}">
<link rel="stylesheet" href="{{ asset('assets/templates/user/css/magnific-popup.css') }}">
